###Intermountain West Shorebird Survey###
#Originally developed by Blake Barbaree, Point Blue Conservation Science, bbarbaree@pointblue.org


##create Year and Season columns
rdf$Date<-as.Date(rdf$Date, format = "%m/%d/%Y")
rdf$Year <- substring(rdf$Date,1,4) 
rdf$Month <- substring(rdf$Date,6,7) 
rdf$Season <- ifelse(rdf$Month == "03", "Spring",
                     ifelse(rdf$Month == "04", "Spring",
                            ifelse(rdf$Month == "05", "Spring",       
                                   ifelse(rdf$Month == "08", "Fall",
                                          ifelse(rdf$Month == "09", "Fall", NA)))))
rdf$SeasonYear <- paste(rdf$Season,rdf$Year)
#long format code for identifying season column
tdf$Date<-as.Date(tdf$Date, format = "%m/%d/%Y")
tdf$Year <- substring(tdf$Date,1,4) 
tdf$Month <- substring(tdf$Date,6,7) 
tdf$Season <- ifelse(tdf$Month == "03", "Spring",
                     ifelse(tdf$Month == "04", "Spring",
                            ifelse(tdf$Month == "05", "Spring",       
                                   ifelse(tdf$Month == "08", "Fall",
                                          ifelse(tdf$Month == "09", "Fall", NA)))))
tdf$SeasonYear <- paste(tdf$Season,tdf$Year)

#Create new columns for "State" and "Site" names using AKN Short Names
#Use a reference table OR the ifelse() statements below. Either way the table/ifelse statements need to be updated when new sites are added

  
##create new column for State based on part of Short Name of Sampling unit in AKN
df$State <- ifelse(grepl("AZ-", df$SamplingUnit, ignore.case = F), 'Arizona',
                  ifelse(grepl("CA-", df$SamplingUnit, ignore.case = F), 'California',
                  ifelse(grepl("CO-", df$SamplingUnit, ignore.case = F), 'Colorado',
                  ifelse(grepl("ID-", df$SamplingUnit, ignore.case = F), 'Idaho',
                  ifelse(grepl("MT-", df$SamplingUnit, ignore.case = F), 'Montana',
                  ifelse(grepl("OR-", df$SamplingUnit, ignore.case = F), 'Oregon',
                  ifelse(grepl("NM-", df$SamplingUnit, ignore.case = F), 'New Mexico',
                  ifelse(grepl("NV-", df$SamplingUnit, ignore.case = F), 'Nevada',
                  ifelse(grepl("UT-", df$SamplingUnit, ignore.case = F), 'Utah',
                  ifelse(grepl("WY-", df$SamplingUnit, ignore.case = F), 'Wyoming',
                  ifelse(grepl("WA-", df$SamplingUnit, ignore.case = F), 'Washington',
                  ifelse(grepl("SS", df$SamplingUnit, ignore.case = F), 'California', ##this line to account for some Salton Sea data
                  NA))))))))))))
  
df$State <- ifelse(grepl("AZ-GANADO", df$SamplingUnit, ignore.case = F),'Navajo Nation',
                  ifelse(grepl("NM-REDLAKE", df$SamplingUnit, ignore.case = F),'Navajo Nation',
                  ifelse(grepl("NM-MORGAN", df$SamplingUnit, ignore.case = F),'Navajo Nation',
                  ifelse(grepl("NV-PL", df$SamplingUnit, ignore.case = F),'Pyramid Lake Paiute Tribe',
                  ifelse(grepl("NV-SUMMIT", df$SamplingUnit, ignore.case = F),'Summit Lake Paiute Tribe',
                  ifelse(grepl("NM-JL", df$SamplingUnit, ignore.case = F),'Jicarilla Apache Nation',
                  ifelse(grepl("MT-NP", df$SamplingUnit, ignore.case = F),'Confederated Salish and Kootenai Tribes',
                  ifelse(grepl("MT-PABLO", df$SamplingUnit, ignore.case = F),'Confederated Salish and Kootenai Tribes',
                  ifelse(grepl("MT-FLATHEAD", df$SamplingUnit, ignore.case = F),'Montana & Confederated Salish and Kootenai Tribes',
                  df$State)))))))))
  
df$Site <- ifelse(grepl("AZ-BA", df$SamplingUnit, ignore.case = F),'Buenos Aires NWR',
                  ifelse(grepl("AZ-ELRIO", df$SamplingUnit, ignore.case = F),'El Rio Preserve',
                  ifelse(grepl("AZ-GILBERT", df$SamplingUnit, ignore.case = F),'Gilbert Riparian Preserve',
                  ifelse(grepl("AZ-CIB", df$SamplingUnit, ignore.case = F),'Cibola NWR',
                  ifelse(grepl("AZ-GLENDALE", df$SamplingUnit, ignore.case = F),'Glendale Recharge Basin',
                  ifelse(grepl("AZ-HAV", df$SamplingUnit, ignore.case = F),'Havasu NWR',
                  ifelse(grepl("AZ-HO", df$SamplingUnit, ignore.case = F),'Higley and Ocotillo WRPs',
                  ifelse(grepl("AZ-IMP", df$SamplingUnit, ignore.case = F),'Imperial NWR',
                  ifelse(grepl("AZ-SANBERN", df$SamplingUnit, ignore.case = F),'San Bernardino NWR',
                  ifelse(grepl("AZ-SWEET", df$SamplingUnit, ignore.case = F),'Sweetwater Wetland',
                  ifelse(grepl("AZ-WHITEWAT", df$SamplingUnit, ignore.case = F),'Whitewater Draw SWA',
                  ifelse(grepl("AZ-WILCOX", df$SamplingUnit, ignore.case = F),'Willcox Playa',
                  ifelse(grepl("CA-ASH", df$SamplingUnit, ignore.case = F),'Ash Creek Wildlife Area',
                  ifelse(grepl("CA-ALK", df$SamplingUnit, ignore.case = F),'Upper Middle Lower Alaki Lakes',
                  ifelse(grepl("CA-ALM", df$SamplingUnit, ignore.case = F),'Lake Almanor Northwest',
                  ifelse(grepl("CA-ALTR", df$SamplingUnit, ignore.case = F),'Alturas Ranches',
                  ifelse(grepl("CA-BLACK", df$SamplingUnit, ignore.case = F),'Black Lake',
                  ifelse(grepl("CA-BPORT", df$SamplingUnit, ignore.case = F),'Bridgeport Reservoir',
                  ifelse(grepl("CA-BIGSAGE", df$SamplingUnit, ignore.case = F),'Big Sage Reservoir',
                  ifelse(grepl("CA-BUTTE", df$SamplingUnit, ignore.case = F),'Butte Valley (Butte Co)',
                  ifelse(grepl("CA-CL", df$SamplingUnit, ignore.case = F),'Clear Lake NWR',
                  ifelse(grepl("CA-CHINALAKE", df$SamplingUnit, ignore.case = F),'China Lake WTP',
                  ifelse(grepl("CA-CROW", df$SamplingUnit, ignore.case = F),'Crowley Lake',
                  ifelse(grepl("CA-DILLON", df$SamplingUnit, ignore.case = F),'Dillon Lake',
                  ifelse(grepl("CA-DONOVAN", df$SamplingUnit, ignore.case = F),'Donovan Reservoir',
                  ifelse(grepl("CA-EDAFB", df$SamplingUnit, ignore.case = F),'Edwards Air Force Base WTP',
                  ifelse(grepl("CA-ECDL", df$SamplingUnit, ignore.case = F),'East Cronese Dry Lake',
                  ifelse(grepl("CA-ELS", df$SamplingUnit, ignore.case = F),'Lake Elsinore',
                  ifelse(grepl("CA-FRV", df$SamplingUnit, ignore.case = F),'Fall River Valley',
                  ifelse(grepl("CA-GOOSE", df$SamplingUnit, ignore.case = F),'Goose Lake',
                  ifelse(grepl("CA-HCG", df$SamplingUnit, ignore.case = F),'Hot Creek Gorge',
                  ifelse(grepl("CA-HDL", df$SamplingUnit, ignore.case = F),'Harper Dry Lake',
                  ifelse(grepl("CA-HL", df$SamplingUnit, ignore.case = F),'Honey Lake',
                  ifelse(grepl("CA-ISA", df$SamplingUnit, ignore.case = F),'Lake Isabella',
                  ifelse(grepl("CA-JLSP", df$SamplingUnit, ignore.case = F),'June Lake WTP',
                  ifelse(grepl("CA-JVM", df$SamplingUnit, ignore.case = F),'Jess Valley Marshes',
                  ifelse(grepl("CA-KB", df$SamplingUnit, ignore.case = F),'Klamath Basin CA',
                  ifelse(grepl("CA-LHC", df$SamplingUnit, ignore.case = F),'Little Hot Creek',
                  ifelse(grepl("CA-LSP", df$SamplingUnit, ignore.case = F),'Lancaster WTP',
                  ifelse(grepl("CA-MADP", df$SamplingUnit, ignore.case = F),'Madeline Plains',
                  ifelse(grepl("CA-ML", df$SamplingUnit, ignore.case = F),'Mono Lake',
                  ifelse(grepl("CA-MOD", df$SamplingUnit, ignore.case = F),'Modoc NWR',                                                                                                                                                                                     ifelse(grepl("CA-NCROW", df$SamplingUnit, ignore.case = F),'Crowley Lake North Ponds ',
                  ifelse(grepl("CA-OL", df$SamplingUnit, ignore.case = F),'Owens Lake',
                  ifelse(grepl("CA-PP", df$SamplingUnit, ignore.case = F),'Piute Ponds',
                  ifelse(grepl("CA-PVV", df$SamplingUnit, ignore.case = F),'Palo Verde Ag Fields',
                  ifelse(grepl("CA-SILVA", df$SamplingUnit, ignore.case = F),'Silva Flat Reservoir',
                  ifelse(grepl("CA-SAID", df$SamplingUnit, ignore.case = F),'Said Valley Reservoir',NA
                  ))))))))))))))))))))))))))))))))))))))))))))))))#49
  
df$Site <- ifelse(grepl("CA-SS", df$SamplingUnit, ignore.case = F),'Salton Sea',
                  ifelse(grepl("CA-SJ", df$SamplingUnit, ignore.case = F),'San Jacinto Wildlife Area',
                  ifelse(grepl("CA-SV", df$SamplingUnit, ignore.case = F),'Sierra Valley',
                  ifelse(grepl("CA-TINE", df$SamplingUnit, ignore.case = F),'Tinemaha Reservoir',
                  ifelse(grepl("CA-TOPAZ", df$SamplingUnit, ignore.case = F),'Topaz Lake',
                  ifelse(grepl("CA-WVR", df$SamplingUnit, ignore.case = F),'West Valley Reservoir',
                  ifelse(grepl("CA-WCWA", df$SamplingUnit, ignore.case = F),'Willow Creek Wildlife Area',
                  ifelse(grepl("CO-ANWR", df$SamplingUnit, ignore.case = F),'Arapaho NWR',
                  ifelse(grepl("CO-BLUEMESA", df$SamplingUnit, ignore.case = F),'Blue Mesa Reservoir Iola Basin',
                  ifelse(grepl("CO-FRUIT", df$SamplingUnit, ignore.case = F),'Fruitgrowers Reservoir',
                  ifelse(grepl("CO-HWA", df$SamplingUnit, ignore.case = F),'Hebron Waterfowl Area',
                  ifelse(grepl("CO-HIGHLINE", df$SamplingUnit, ignore.case = F),'Highline Reservoir',
                  ifelse(grepl("CO-JOHN", df$SamplingUnit, ignore.case = F),'Lake John',
                  ifelse(grepl("CO-RIOBLANCO", df$SamplingUnit, ignore.case = F),'Rio Blanco SWA',
                  ifelse(grepl("CO-WALDEN", df$SamplingUnit, ignore.case = F),'Walden Reservoir',
                  ifelse(grepl("ID-AF", df$SamplingUnit, ignore.case = F),'American Falls',
                  ifelse(grepl("ID-BL", df$SamplingUnit, ignore.case = F),'Bear Lake NWR',
                  ifelse(grepl("ID-BCR", df$SamplingUnit, ignore.case = F),'Blacks Creek Reservoir',
                  ifelse(grepl("ID-BRNOTUS", df$SamplingUnit, ignore.case = F),'Boise River Rd SW of Notus',
                  ifelse(grepl("ID-BSDSP", df$SamplingUnit, ignore.case = F),'Bruneau Sand Dunes State Park',
                  ifelse(grepl("ID-CLEAR", df$SamplingUnit, ignore.case = F),'Clearwater River',
                  ifelse(grepl("ID-CPCM", df$SamplingUnit, ignore.case = F),'Camas Prairie Centennial Marsh WMA',
                  ifelse(grepl("ID-DLN", df$SamplingUnit, ignore.case = F),'Dry Lakes North of Nampa',
                  ifelse(grepl("ID-DVR", df$SamplingUnit, ignore.case = F),'Duck Valley Reservation',
                  ifelse(grepl("ID-FBW", df$SamplingUnit, ignore.case = F),'Fort Boise WMA',
                  ifelse(grepl("ID-GEMSP", df$SamplingUnit, ignore.case = F),'Gem St Academy Sewage Ponds', 
                  ifelse(grepl("ID-GL", df$SamplingUnit, ignore.case = F),'Grays Lake NWR',
                  ifelse(grepl("ID-HUBR", df$SamplingUnit, ignore.case = F),'Hubbard Reservoir',
                  ifelse(grepl("ID-IDFF", df$SamplingUnit, ignore.case = F),'Agricultural fields W of Idaho Falls',
                  ifelse(grepl("ID-INCR", df$SamplingUnit, ignore.case = F),'Indian Creek Reservoir',
                  ifelse(grepl("ID-LCR", df$SamplingUnit, ignore.case = F),'Little Camas Reservoir',
                  ifelse(grepl("ID-LMNWR", df$SamplingUnit, ignore.case = F),'Lee Metcalf NWR',
                  ifelse(grepl("ID-LOWELL", df$SamplingUnit, ignore.case = F),'Deer Flat NWR - Lake Lowell',
                  ifelse(grepl("ID-LVR", df$SamplingUnit, ignore.case = F),'Little Valley Reservoir',
                  ifelse(grepl("ID-MNL", df$SamplingUnit, ignore.case = F),'Mann Lake',
                  ifelse(grepl("ID-MKTL", df$SamplingUnit, ignore.case = F),'Market Lake WMA',
                  ifelse(grepl("ID-MINI", df$SamplingUnit, ignore.case = F),'Minidoka NWR',
                  ifelse(grepl("ID-MLWMA", df$SamplingUnit, ignore.case = F),'Mud Lake WMA',
                  ifelse(grepl("ID-MORM", df$SamplingUnit, ignore.case = F),'Mormon Reservoir',
                  ifelse(grepl("ID-MACKAY", df$SamplingUnit, ignore.case = F),'Mackay Reservoir',
                  ifelse(grepl("ID-MTHR", df$SamplingUnit, ignore.case = F),'Mt Home Reservoir',
                  ifelse(grepl("ID-OXSL", df$SamplingUnit, ignore.case = F),'Oxford Slough',
                  ifelse(grepl("ID-RMWMA", df$SamplingUnit, ignore.case = F),'Roswell Marsh WHA',
                  ifelse(grepl("ID-TOLO", df$SamplingUnit, ignore.case = F),'Tolo Lake',
                  ifelse(grepl("ID-WDP", df$SamplingUnit, ignore.case = F),'Wilson Drainage Pond',
                  ifelse(grepl("MT-BL", df$SamplingUnit, ignore.case = F),'Benton Lake NWR',
                  ifelse(grepl("MT-BIG", df$SamplingUnit, ignore.case = F),'Big Lake - Grass Lake NWR', df$Site
                  )))))))))))))))))))))))))))))))))))))))))))))))#47
  
df$Site <- ifelse(grepl("MT-BOWDOIN", df$SamplingUnit, ignore.case = F),'Bowdoin NWR',
                  ifelse(grepl("MT-CFL", df$SamplingUnit, ignore.case = F),'Canyon Ferry Lake',
                  ifelse(grepl("MT-CLARK", df$SamplingUnit, ignore.case = F),'Clark Canyon Reservoir',
                  ifelse(grepl("MT-COTTONW", df$SamplingUnit, ignore.case = F),'Cottonwood Reservoir',
                  ifelse(grepl("MT-ENNIS", df$SamplingUnit, ignore.case = F),'Ennis Lake',
                  ifelse(grepl("MT-FLATHEAD", df$SamplingUnit, ignore.case = F),'Flathead Lake',
                  ifelse(grepl("MT-FOL", df$SamplingUnit, ignore.case = F),'Freezeout Lake WMA',
                  ifelse(grepl("MT-GOOSELAKE", df$SamplingUnit, ignore.case = F),'Goose Lake wetland complex',
                  ifelse(grepl("MT-HARWILLOW", df$SamplingUnit, ignore.case = F),'Harrison/Willow Creek Reservoir',
                  ifelse(grepl("MT-MEDICINE", df$SamplingUnit, ignore.case = F),'Medicine Lake NWR Complex',
                  ifelse(grepl("MT-NELSON", df$SamplingUnit, ignore.case = F),'Nelson Reservoir',
                  ifelse(grepl("MT-NP", df$SamplingUnit, ignore.case = F),'Ninepipe NWR & WMA',
                  ifelse(grepl("MT-PABLO", df$SamplingUnit, ignore.case = F),'Pablo NWR',
                  ifelse(grepl("MT-SPIDEL", df$SamplingUnit, ignore.case = F),'Spidel WPA',
                  ifelse(grepl("MT-SYME", df$SamplingUnit, ignore.case = F),'Syme Slough',
                  ifelse(grepl("MT-WSP", df$SamplingUnit, ignore.case = F),'Warm Springs Reservoir (MT)',
                  ifelse(grepl("NM-BDA", df$SamplingUnit, ignore.case = F),'Bosque del Apache NWR',
                  ifelse(grepl("NM-BN", df$SamplingUnit, ignore.case = F),'Bernardo WMA',
                  ifelse(grepl("NM-BL", df$SamplingUnit, ignore.case = F),'Bitter Lake NWR',
                  ifelse(grepl("NM-HOL", df$SamplingUnit, ignore.case = F),'Holloman Lake',
                  ifelse(grepl("NM-JL", df$SamplingUnit, ignore.case = F),'Jicarilla Lakes',
                  ifelse(grepl("NM-LJ", df$SamplingUnit, ignore.case = F),'La Joya WMA',
                  ifelse(grepl("NM-LVR", df$SamplingUnit, ignore.case = F),'Las Vegas NWR',
                  ifelse(grepl("NM-MAX", df$SamplingUnit, ignore.case = F),'Maxwell NWR',
                  ifelse(grepl("NM-MORGAN", df$SamplingUnit, ignore.case = F),'Morgan Lake',
                  ifelse(grepl("NM-SALTLAKES", df$SamplingUnit, ignore.case = F),'Big Salt Lake area',
                  ifelse(grepl("NM-WSH", df$SamplingUnit, ignore.case = F),'W.S. Huey WMA',
                  ifelse(grepl("NV-23MILE", df$SamplingUnit, ignore.case = F),'23 Mile Reservoir',
                  ifelse(grepl("NV-ARTESIA", df$SamplingUnit, ignore.case = F),'Artesia Lake',
                  ifelse(grepl("NV-ASH", df$SamplingUnit, ignore.case = F),'Ash Meadows NWR',
                  ifelse(grepl("NV-BASSETT", df$SamplingUnit, ignore.case = F),'Bassett Lake and Slough',
                  ifelse(grepl("NV-BLUE", df$SamplingUnit, ignore.case = F),'Blue Lakes',
                  ifelse(grepl("NV-BOYD", df$SamplingUnit, ignore.case = F),'Boyd Reservoir',
                  ifelse(grepl("NV-COLDSPR", df$SamplingUnit, ignore.case = F),'White Lake (Cold Springs playa)',
                  ifelse(grepl("NV-COMINS", df$SamplingUnit, ignore.case = F),'Comins Lake area',
                  ifelse(grepl("NV-CONTIN", df$SamplingUnit, ignore.case = F),'Continental Lake',
                  ifelse(grepl("NV-CRINTEN", df$SamplingUnit, ignore.case = F),'Crintendon Reservoir',
                  ifelse(grepl("NV-DAKE", df$SamplingUnit, ignore.case = F),'Dake Reservoir',
                  ifelse(grepl("NV-DEERCR", df$SamplingUnit, ignore.case = F),'Deer Creek Reservoir',
                  ifelse(grepl("NV-DIAMOND", df$SamplingUnit, ignore.case = F),'Diamond Valley (Playa Wells)',
                  ifelse(grepl("NV-GLENDALE", df$SamplingUnit, ignore.case = F),'Glendale Pond',
                  ifelse(grepl("NV-GOSHUTE", df$SamplingUnit, ignore.case = F),'Goshute Lake area',
                  ifelse(grepl("NV-GRIDLEY", df$SamplingUnit, ignore.case = F),'Gridley Lake',
                  ifelse(grepl("NV-HENDSP", df$SamplingUnit, ignore.case = F),'Henderson Sewage Ponds',
                  ifelse(grepl("NV-HOGJOHN", df$SamplingUnit, ignore.case = F),'Hog John Slough - Quinn Lakes',
                  ifelse(grepl("NV-HUM", df$SamplingUnit, ignore.case = F),'Humboldt WMA',
                  ifelse(grepl("NV-ILLI", df$SamplingUnit, ignore.case = F),'Illipah Reservoir',
                  ifelse(grepl("NV-JAKESCR", df$SamplingUnit, ignore.case = F),'Jakes Creek Reservoir',
                  ifelse(grepl("NV-JDRP", df$SamplingUnit, ignore.case = F),'J.D. Ranch pond', df$Site
                  )))))))))))))))))))))))))))))))))))))))))))))))))#49
  
df$Site <- ifelse(grepl("NV-JIGGS", df$SamplingUnit, ignore.case = F),'Zunino Reservoir (Jiggs)',        
                  ifelse(grepl("NV-KP", df$SamplingUnit, ignore.case = F),'Key Pittman WMA',
                  ifelse(grepl("NV-LM", df$SamplingUnit, ignore.case = F),'Lake Mead NRA',
                  ifelse(grepl("NV-LOGENDALE", df$SamplingUnit, ignore.case = F),'Bowman Reservoir (Logendale)',
                  ifelse(grepl("NV-LV", df$SamplingUnit, ignore.case = F),'Lahontan Valley',
                  ifelse(grepl("NV-LONGVAL", df$SamplingUnit, ignore.case = F),'Long Valley',
                  ifelse(grepl("NV-LSLOUGH", df$SamplingUnit, ignore.case = F),'Long Valley Slough',
                  ifelse(grepl("NV-MARYSRV", df$SamplingUnit, ignore.case = F),'Marys River',
                  ifelse(grepl("NV-MASON", df$SamplingUnit, ignore.case = F),'Mason Valley WMA',
                  ifelse(grepl("NV-MASS", df$SamplingUnit, ignore.case = F),'Massacre Lake',
                  ifelse(grepl("NV-MUDLAKE", df$SamplingUnit, ignore.case = F),'Mud Lake',
                  ifelse(grepl("NV-MUDMEADOW", df$SamplingUnit, ignore.case = F),'Mud Meadow Reservoir',
                  ifelse(grepl("NV-NYEAR", df$SamplingUnit, ignore.case = F),'New Years Lake',
                  ifelse(grepl("NV-OV", df$SamplingUnit, ignore.case = F),'Overton WMA',
                  ifelse(grepl("NV-PAHR", df$SamplingUnit, ignore.case = F),'Pahranagat NWR',
                  ifelse(grepl("NV-PARKER", df$SamplingUnit, ignore.case = F),'Parker Reservoir',
                  ifelse(grepl("NV-PL", df$SamplingUnit, ignore.case = F),'Pyramid Lake',
                  ifelse(grepl("NV-RV", df$SamplingUnit, ignore.case = F),'Ruby Valley',
                  ifelse(grepl("NV-SETTEL", df$SamplingUnit, ignore.case = F),'Settelmeyer Ranches',
                  ifelse(grepl("NV-SFHUMBOLD", df$SamplingUnit, ignore.case = F),'South Fork Humboldt River SRA',
                  ifelse(grepl("NV-SFORK", df$SamplingUnit, ignore.case = F),'South Fork Reservoir',
                  ifelse(grepl("NV-SH", df$SamplingUnit, ignore.case = F),'Sheldon NWR',
                  ifelse(grepl("NV-SLEEP", df$SamplingUnit, ignore.case = F),'Sleeper Mine',
                  ifelse(grepl("NV-SMOKECR", df$SamplingUnit, ignore.case = F),'Smoke Creek Desert',
                  ifelse(grepl("NV-SNOWWATER", df$SamplingUnit, ignore.case = F),'Snow Water Lake',
                  ifelse(grepl("NV-SOLDIER", df$SamplingUnit, ignore.case = F),'Soldier Meadows',
                  ifelse(grepl("NV-SPRINGS", df$SamplingUnit, ignore.case = F),'Springs Preserve (former Las Vegas SP',
                  ifelse(grepl("NV-SUMMIT", df$SamplingUnit, ignore.case = F),'Summit Lake',
                  ifelse(grepl("NV-SWL", df$SamplingUnit, ignore.case = F),'Swan Lake NSA',
                  ifelse(grepl("NV-ULVW", df$SamplingUnit, ignore.case = F),'Upper Las Vegas Wash',
                  ifelse(grepl("NV-WABUSKA", df$SamplingUnit, ignore.case = F),'Wabuska Marshes',
                  ifelse(grepl("NV-WARMSPR", df$SamplingUnit, ignore.case = F),'Warm Springs Reservoir',
                  ifelse(grepl("NV-WASH", df$SamplingUnit, ignore.case = F),'Washoe Lake wetlands',
                  ifelse(grepl("NV-WEBER", df$SamplingUnit, ignore.case = F),'Weber Reservoir',
                  ifelse(grepl("NV-WELLSWTP", df$SamplingUnit, ignore.case = F),'Wells WTP',
                  ifelse(grepl("NV-WILDHORSE", df$SamplingUnit, ignore.case = F),'Wildhorse Reservoir SRA',
                  ifelse(grepl("NV-WHITE", df$SamplingUnit, ignore.case = F),'White Lake',
                  ifelse(grepl("NV-WILSON", df$SamplingUnit, ignore.case = F),'Wilson Reservoir SRA',
                  ifelse(grepl("NV-WINNEMUCC", df$SamplingUnit, ignore.case = F),'Winnemucca Lake',
                  ifelse(grepl("NV-WL", df$SamplingUnit, ignore.case = F),'Walker Lake',
                  ifelse(grepl("NV-WWENDWTP", df$SamplingUnit, ignore.case = F),'West Wendover WTP',
                  ifelse(grepl("NV-ZAGA", df$SamplingUnit, ignore.case = F),'Zaga Ranch Pond',
                  ifelse(grepl("OR-ABERT", df$SamplingUnit, ignore.case = F),'Lake Abert',
                  ifelse(grepl("OR-ALKALI", df$SamplingUnit, ignore.case = F),'Alkali Lakes',
                  ifelse(grepl("OR-ALKDAIRY", df$SamplingUnit, ignore.case = F),'Alkali lake near Dairy',
                  ifelse(grepl("OR-ANTELOPE", df$SamplingUnit, ignore.case = F),'Antelope Reservoir',
                  ifelse(grepl("OR-BULLYCR", df$SamplingUnit, ignore.case = F),'Bully Creek Reservoir',
                  ifelse(grepl("OR-BURNS", df$SamplingUnit, ignore.case = F),'Burns Sewage Ponds', df$Site
                  ))))))))))))))))))))))))))))))))))))))))))))))))#48
  
df$Site <- ifelse(grepl("OR-COLDSPR", df$SamplingUnit, ignore.case = F),'Cold Springs NWR',       
                ifelse(grepl("OR-CRANE", df$SamplingUnit, ignore.case = F),'Crane Creek Hot Springs',
                ifelse(grepl("OR-DREWS", df$SamplingUnit, ignore.case = F),'Drews Reservoir',
                ifelse(grepl("OR-HB", df$SamplingUnit, ignore.case = F),'Harney Basin',
                ifelse(grepl("OR-KB", df$SamplingUnit, ignore.case = F),'Klamath Basin',
                ifelse(grepl("OR-MALHEURLK", df$SamplingUnit, ignore.case = F),'Malheur Lake and NWR',
                ifelse(grepl("OR-SUM", df$SamplingUnit, ignore.case = F),'Summer Lake',
                ifelse(grepl("OR-UMATILLA", df$SamplingUnit, ignore.case = F),'Umatilla NWR',
                ifelse(grepl("OR-WARMSPR", df$SamplingUnit, ignore.case = F),'Warm Springs Reservoir (OR)',
                ifelse(grepl("OR-WV", df$SamplingUnit, ignore.case = F),'Warner Valley',
                ifelse(grepl("UT-ABS", df$SamplingUnit, ignore.case = F),'Amalga Barrens Sanctuary',
                ifelse(grepl("UT-FS", df$SamplingUnit, ignore.case = F),'Fish Springs NWR',
                ifelse(grepl("UT-GSL", df$SamplingUnit, ignore.case = F),'Great Salt Lake',
                ifelse(grepl("UT-UTL", df$SamplingUnit, ignore.case = F),'Utah Lake',
                ifelse(grepl("WA-ANATONE", df$SamplingUnit, ignore.case = F),'Anatone Ponds',
                ifelse(grepl("WA-BYRON", df$SamplingUnit, ignore.case = F),'Byron Ponds complex',
                ifelse(grepl("WA-COLUMBIA", df$SamplingUnit, ignore.case = F),'Columbia NWR',
                ifelse(grepl("WA-CRABHWY26", df$SamplingUnit, ignore.case = F),'Crab Creek Hwy 26 ponds',
                ifelse(grepl("WA-DODSONRD", df$SamplingUnit, ignore.case = F),'Dodson Road Wasteways',
                ifelse(grepl("WA-HANFOSAD", df$SamplingUnit, ignore.case = F),'Hanford Reach and Saddle Mtn NWR',
                ifelse(grepl("WA-KAHLOTUS", df$SamplingUnit, ignore.case = F),'Kahlotus Lake',
                ifelse(grepl("WA-OTHELLOSP", df$SamplingUnit, ignore.case = F),'Othello Sewage Ponds',
                ifelse(grepl("WA-POTH", df$SamplingUnit, ignore.case = F),'Potholes Reservoir',
                ifelse(grepl("WA-PRIEST", df$SamplingUnit, ignore.case = F),'Priest Rapids Lake',
                ifelse(grepl("WA-REARDON", df$SamplingUnit, ignore.case = F),'Reardon Ponds',
                ifelse(grepl("WA-SALTESE", df$SamplingUnit, ignore.case = F),'Saltese Flats',
                ifelse(grepl("WA-SAVAGE", df$SamplingUnit, ignore.case = F),'Savage Rd pond',
                ifelse(grepl("WA-SNAKE", df$SamplingUnit, ignore.case = F),'Snake River',
                ifelse(grepl("WA-SOAP", df$SamplingUnit, ignore.case = F),'Soap Lake',
                ifelse(grepl("WA-WALLA", df$SamplingUnit, ignore.case = F),'Walla Walla River Delta',
                ifelse(grepl("WA-YAKIMARV", df$SamplingUnit, ignore.case = F),'Yakima River Delta',
                ifelse(grepl("WY-ABL", df$SamplingUnit, ignore.case = F),'Alkali & Beck Lakes',
                ifelse(grepl("WY-BAMFORTH", df$SamplingUnit, ignore.case = F),'Bamforth NWR',
                ifelse(grepl("WY-DR", df$SamplingUnit, ignore.case = F),'Deaver Reservoir',
                ifelse(grepl("WY-BEARWET", df$SamplingUnit, ignore.case = F),'Bear River Valley Wetlands/ Cokeville Meadows NWR',
                ifelse(grepl("WY-HLNWR", df$SamplingUnit, ignore.case = F),'Hutton Lake NWR',
                ifelse(grepl("WY-LARPL", df$SamplingUnit, ignore.case = F),'Laramie Plains Lakes',
                ifelse(grepl("WY-LL", df$SamplingUnit, ignore.case = F),'Lovell Lakes',
                ifelse(grepl("WY-MORT", df$SamplingUnit, ignore.case = F),'Mortenson Lake NWR',
                ifelse(grepl("WY-PATH", df$SamplingUnit, ignore.case = F),'Pathfinder NWR',
                ifelse(grepl("WY-TABLE", df$SamplingUnit, ignore.case = F),'Table Mountain WMA',
                ifelse(grepl("WY-WARDELL", df$SamplingUnit, ignore.case = F),'Wardell/Harrington Reservoirs',
                ifelse(grepl("WY-WOODRUFF", df$SamplingUnit, ignore.case = F),'Woodruff Narrows Reservoir',
                ifelse(grepl("NV-DUCKFLAT", df$SamplingUnit, ignore.case = F),'Duck Flat',
                ifelse(grepl("OR-COWL", df$SamplingUnit, ignore.case = F),'Cow Lakes',
                ifelse(grepl("MT-LM", df$SamplingUnit, ignore.case = F),'Lee Metcalf NWR',
                ifelse(grepl("OR-MALHEURRE", df$SamplingUnit, ignore.case = F),'Malheur Reservoir',
                ifelse(grepl("NM-CABALLO", df$SamplingUnit, ignore.case = F),'Caballo Lake',
                ifelse(grepl("CA-EAGLE", df$SamplingUnit, ignore.case = F),'Eagle Lake',df$Site  ## last line to SSSS project data
                )))))))))))))))))))))))))))))))))))))))))))))))))#49
  
df$Site <- ifelse(grepl("CA-MOON", df$SamplingUnit, ignore.case = F),'Moon Lake',
                ifelse(grepl("ID-MGCR", df$SamplingUnit, ignore.case = F),'Magic Reservoir',
                ifelse(grepl("MT-BOWDOIN", df$SamplingUnit, ignore.case = F),'Bowdoin NWR',
                ifelse(grepl("NV-LEMMON", df$SamplingUnit, ignore.case = F),'Lemmon Valley',
                ifelse(grepl("OR-LAKEVWTP", df$SamplingUnit, ignore.case = F),'Lakeview WTP',
                ifelse(grepl("OR-WILLOW", df$SamplingUnit, ignore.case = F),'Willow Valley Reservoir',
                ifelse(grepl("NV-BULL", df$SamplingUnit, ignore.case = F),'Bull Run Reservoir',
                ifelse(grepl("NV-WILLOW", df$SamplingUnit, ignore.case = F),'Willow Creek Reservoir',
                ifelse(grepl("CA-HORSE", df$SamplingUnit, ignore.case = F),'Horse Lake',
                ifelse(grepl("CA-MUDFLAT", df$SamplingUnit, ignore.case = F),'Mud Flat',
                ifelse(grepl("OR-CHEW", df$SamplingUnit, ignore.case = F),'Chewaucan Marsh',
                ifelse(grepl("CA-BVWA", df$SamplingUnit, ignore.case = F),'Butte Valley Wildlife Area',
                ifelse(grepl("NM-REDLAKE", df$SamplingUnit, ignore.case = F),'Red Lake',
                ifelse(grepl("AZ-GANADO", df$SamplingUnit, ignore.case = F),'Ganado Lake',
                ifelse(grepl("OR-YO", df$SamplingUnit, ignore.case = F),'Yonna Valley',                  
                ifelse(grepl("NM-COCH", df$SamplingUnit, ignore.case = F),'Cochiti Lake',
                ifelse(grepl("NM-ESTANCIA", df$SamplingUnit, ignore.case = F),'Lake Estancia',
                ifelse(grepl("WA-SWWA", df$SamplingUnit, ignore.case = F),'Swanson Lakes Wildlife Area',
                ifelse(grepl("MT-ENNIS", df$SamplingUnit, ignore.case = F),'Ennis Lake',
                ifelse(grepl("ID-CNWR", df$SamplingUnit, ignore.case = F),'Camas NWR',
                ifelse(grepl("ID-PADDOCK", df$SamplingUnit, ignore.case = F),'Paddock Valley',
                ifelse(grepl("ID-BENROSS", df$SamplingUnit, ignore.case = F),'Ben Ross Reservoir',
                ifelse(grepl("ID-CCADE", df$SamplingUnit, ignore.case = F),'Lake Cascade',
                                                                                                                                                                              ifelse(grepl("ID-SIMPLOT", df$SamplingUnit, ignore.case = F),'Simplot Pastures',
                                                                                                                                                                                     ifelse(grepl("WA-SHEEP", df$SamplingUnit, ignore.case = F),'Sheep Lake',
                                                                                                                                                                                            ifelse(grepl("WA-CROOKED", df$SamplingUnit, ignore.case = F),'Crooked Knee Lake',
                                                                                                                                                                                                   ifelse(grepl("WA-COW", df$SamplingUnit, ignore.case = F),'Cow Lake',
                                                                                                                                                                                                          ifelse(grepl("WA-ROCK", df$SamplingUnit, ignore.case = F),'Rock Creek at Hwy 23',
                                                                                                                                                                                                                 ifelse(grepl("WA-SPRAGUE", df$SamplingUnit, ignore.case = F),'Sprague Lake',
                                                                                                                                                                                                                        ifelse(grepl("WA-SSTP", df$SamplingUnit, ignore.case = F),'Sprague STP',
                                                                                                                                                                                                                               ifelse(grepl("WA-MCCAIN", df$SamplingUnit, ignore.case = F),'McCain Ponds',
                                                                                                                                                                                                                                      ifelse(grepl("WA-CSTP", df$SamplingUnit, ignore.case = F),'Connell STP',
                                                                                                                                                                                                                                             ifelse(grepl("WA-LIND", df$SamplingUnit, ignore.case = F),'Lind Coulee',
                                                                                                                                                                                                                                                    ifelse(grepl("WA-CCSTP", df$SamplingUnit, ignore.case = F),'Coulee City STP',                  
                                                                                                                                                                                                                                                           ifelse(grepl("WA-RICHAP", df$SamplingUnit, ignore.case = F),'Richland Asphalt Ponds',
                                                                                                                                                                                                                                                                  ifelse(grepl("OR-GERBER", df$SamplingUnit, ignore.case = F),'Gerber Reservoir',
                                                                                                                                                                                                                                                                         ifelse(grepl("OR-RRR", df$SamplingUnit, ignore.case = F),'Rivers End Ranch',
                                                                                                                                                                                                                                                                                ifelse(grepl("OR-RICHAP", df$SamplingUnit, ignore.case = F),'Richarson Asphalt Ponds',
                                                                                                                                                                                                                                                                                       ifelse(grepl("ID-CAREY", df$SamplingUnit, ignore.case = F),'Carey Lake',
                                                                                                                                                                                                                                                                                              ifelse(grepl("ID-CRANECREE", df$SamplingUnit, ignore.case = F),'Crane Creek Reservoir',
                                                                                                                                                                                                                                                                                                     ifelse(grepl("ID-TT", df$SamplingUnit, ignore.case = F),'Ted Trueblood WHA',
                                                                                                                                                                                                                                                                                                            ifelse(grepl("ID-CRANECREE", df$SamplingUnit, ignore.case = F),'Crane Creek Reservoir',
                                                                                                                                                                                                                                                                                                                   ifelse(grepl("UT-BL", df$SamplingUnit, ignore.case = F),'Blue Lake',
                                                                                                                                                                                                                                                                                                                          ifelse(grepl("UT-OR", df$SamplingUnit, ignore.case = F),'Olsen Reservoir',
                                                                                                                                                                                                                                                                                                                                 ifelse(grepl("CO-SLV-ALAMO", df$SamplingUnit, ignore.case = F),'Alamosa NWR',
                                                                                                                                                                                                                                                                                                                                        ifelse(grepl("CO-SLV-BLANC", df$SamplingUnit, ignore.case = F),'Blanca Wetlands',
                                                                                                                                                                                                                                                                                                                                               ifelse(grepl("CO-SLV-MVNWR", df$SamplingUnit, ignore.case = F),'Monte Vista NWR',
                                                                                                                                                                                                                                                                                                                                                      ifelse(grepl("CO-SLV-RL", df$SamplingUnit, ignore.case = F),'Russell Lakes SWA',
                                                                                                                                                                                                                                                                                                                                                             ifelse(grepl("CO-SLV-SLLAK", df$SamplingUnit, ignore.case = F),'San Luis Lakes SWA',
                                                                                                                                                                                                                                                                                                                                                                    df$Site)))))))))))))))))))))))))))))))))))))))))))))))))#49
df$Site <- ifelse(grepl("WY-BUMPSUL", df$SamplingUnit, ignore.case = F),'Bump-Sullivan Reservoir',
                    ifelse(grepl("ID-SOLDMED", df$SamplingUnit, ignore.case = F),'Soldier Meadows',
                    ifelse(grepl("WY-BURL", df$SamplingUnit, ignore.case = F),'Burlington Lake',
                    ifelse(grepl("NV-NEWARK", df$SamplingUnit, ignore.case = F),'Newark Valley',
                    ifelse(grepl("ID-BDP", df$SamplingUnit, ignore.case = F),'Bruneau Duck Ponds',
                    ifelse(grepl("CO-SAMB", df$SamplingUnit, ignore.case = F),'Sambrito Wetlands',
                    ifelse(grepl("ID-WIN", df$SamplingUnit, ignore.case = F),'Winchester Lake',
                    ifelse(grepl("WA-GRSP", df$SamplingUnit, ignore.case = F),'Grandview Sewage Ponds',
                                  df$Site))))))))#8
  
  
  
##check for errors in State and Site names
df$State <- as.factor(df$State)
summary(df$State)
df$Site <- as.factor(df$Site)
summary(df$Site)
df$SamplingUnit <- as.factor(df$SamplingUnit)